### ISSUE TITLE
Version reported as `unknown` at least on 1.28.0 on Linux x64

### ISSUE THREAD

**Issue by mattpodraza** [neondatabase/neonctl#196]
## Steps to reproduce
Run `neonctl -v`

## Expected result
Something along the lines of:
```
❯ neonctl -v
1.28.0
```
## Actual result
```
❯ neonctl -v
unknown
```

## Environment
- Fedora 39 x64
- Node 20.9.0

I haven't tested the other builds or other versions to see if this is just an issue with 1.28.0

**Comment by mrl5** [comment]
I was able to reproduce with `1.36.0`. Root cause seams to be default behavior of https://yargs.js.org/docs/#api-reference-versionoption-description-version
> If no arguments are passed to version (.version()), yargs will parse the package.json of your module and use its version value.

which seams to be doing a lookup of nearest `package.json`.


Since `neonctl` is installed somewhere in `node_modules`, the result of `npx neonctl --version` can be either `unknown` or version in nearest `package.json`.

### steps to reproduce
```console
mkdir foo && cd $_
npm init --yes
npm install neonctl@1.36.0
npx neonctl --version
```

### expected
```console
1.36.0
```

### actual
```console
1.0.0
```
